check the vvdec build problem

diff --git a/.github/workflows/mpv_clang.yml b/.github/workflows/mpv_clang.yml
--- a/.github/workflows/mpv_clang.yml
+++ b/.github/workflows/mpv_clang.yml
@@ -105,8 +105,13 @@ jobs:
         env:
           MPV_TARBALL: ${{ github.event.inputs.mpv_tarball }}
         run: |
+          set -e
           ninja -C build_$BIT update
-          $MPV_TARBALL && ninja -C build_$BIT mpv-release || ninja -C build_$BIT mpv
+          if ! ($MPV_TARBALL && ninja -C build_$BIT mpv-release || ninja -C build_$BIT mpv); then
+            echo "Build failed, showing vvdec build log:"
+            cat build_$BIT/packages/vvdec-prefix/src/vvdec-stamp/vvdec-build-*.log || true
+            exit 1
+          fi
           $MPV_TARBALL && echo "mpv_ver=$(cat build_$BIT/packages/mpv-release-prefix/VERSION)" >> $GITHUB_OUTPUT || echo "mpv_ver=UNKNOWN" >> $GITHUB_OUTPUT
 
       - name: Packaging mpv
